### PR TITLE
Fixing itemLimit Validation in case extraButtons Option

### PR DESCRIPTION
**Pull request by stevenAric**
1. the Issue: 
the issue is that when defining extraButtons options with validation rules in , the itemLimit Property Rules isn't working and the only working validation limit is the main itemLimit in general Validation option.
2. a reference to the issue: 
https://github.com/FineUploader/fine-uploader/issues/1756

3.  browsers and operating systems: 

firefox , Chrome, Edge on Windows 7

4.the new file here  , 
https://github.com/stevenAric/fine-uploader/blob/develop/fine-uploader.js

### CODE REVIEW

**Comment by rnicholus** [comment]
looks like you have created two PRs for the same issue - please close one.

**Comment by stevenAric** [comment]
@rnicholus  : i closed the first and here is the second , and after this pull request ended , i will start create a new function called deattachForm() , that release the attached form either by element option or by setForm function, i am waiting for your response.

**Comment by rnicholus** [comment]
May be a little while before I can take a look at this one - there are a number of others ahead in my queue, but it's on my list. Thanks for your patience.

**Comment by stevenAric** [comment]
Never Mind , Take Your Time.

**Comment by rnicholus** [comment]
Sorry, I can't accept this. It looks like you've simply attached a patched version of one of the many built versions of Fine Uploader. Pull requests should include modifications to one or more of the source files, in the client directory of the project.

**Pull request closed without merging**
