### PR TITLE
Fixed Drag'n'Drop for Firefox 54

### PR DESCRIPTION
**Pull request by SpazzMarticus**
## Brief description of the changes
Fix for #1862 
Reordered checks in `leavingDocumentOut` in order to try use `e.x` and `e.y`, before falling back on `e.relatedTarget`.

## What browsers and operating systems have you tested these changes on?
Windows 8.1 x64 - Worked with Firefox 47 **and** 54. 
_I don't know if this has anything to do with it: https://bugzilla.mozilla.org/show_bug.cgi?id=962251)_
(Works in Chrome 59 too.)

## Have you written unit tests? If not, explain why.
Did not find any unit tests for drag and drop.

### CODE REVIEW

**Comment by cubiclesoft** [comment]
A change in drag-and-drop support - one of the core features of a file uploader - needs to be tested widely across all browsers with as many versions as is reasonably possible.  This PR seems like a rather significant change to just accept into mainline with such minimal testing.  A less invasive approach would be to isolate just Firefox using the existing `qq.firefox()` check.

**Comment by maximilianschmid** [comment]
Tested patch successfully on 

- IE11 Win732bit
- FF 55 Mac
- FF 55 32bit Win732bit
- FF 30 Win732bit
- Safari 10.1
- Google Chrome 60  Mac & Win

**Comment by rnicholus** [comment]
I’d like some explanation regarding the details of this fix. It’s not clear to me why this fixes the issue, which I have not verified myself.

**Comment by SpazzMarticus** [comment]
My fix does not work correctly any more in Firefox 56 (x64, Win) any more, because when leaving the browser window I get this error: [`Permission denied to access property "x"`](https://github.com/SpazzMarticus/fine-uploader/blob/8a809af1b2d4ad0e8d614406e5b33f2975e1c238/client/js/dnd.js#L222)
It solves the anoying flickering problem, but does not hide the Drop-Zone when leaving the browser window.

Also in Firefox 56 (x64, Ubuntu 17) the `x` and `y` are not set to 0 or negative values when leaving the browser window.

I hope you can fix this problem!

**Pull request closed without merging**
