### PR TITLE
Double Thumbnail loading (#1936) Fix

### PR DESCRIPTION
**Pull request by blacktoby**
See Issue #1936 for more Infos

## Brief description of the changes
Changes related to #1936 

## What browsers and operating systems have you tested these changes on?
Chrome on MacOS

## Have you written unit tests? If not, explain why.
I have not written unit tests, because I dont have the complete overview over the code and do not have the time to working into it and setting up a proper environment to develop tests for this piece of code.
The fix I presented in #1936 is just a suggestion and is working in my situation. There should be someone other, who looks at it and test the change with a look at the full code.

### CODE REVIEW

**Comment by rnicholus** [comment]
Please explain your change in detail (the logic behind it, etc).

**Comment by blacktoby** [comment]
I searched a way to avoid duplicate adding Thumbnails to the `thumbGenerationQueue`. 
I saw that the `updateThumbnail` is called two times:
One time in `_addToList`  and one time in `_maybeUpdateThumbnail` (part of `qq.uiPrivateApi`). 
`_addToList` is called when `_onSubmit` runs and `_maybeUpdateThumbnail` is called when `_markFileAsSuccessful` runs.
At this point I dont have a deeper look how fineuploader is working. So I just compared the parameters given when `updateThumbnail` is called. I saw that the first time `showWaitingImg` is true and the second time undefined.
I also observed, that the second call of the update Function is not necessary to show the thumbnail image. So I just excluded the second push to the queue with:
```
if(showWaitingImg !== true) { return; }
```
May be not the best way to handle this problem. For me it was the best way to get this problem solved, without deep dive into the code and change major procedures.

**Comment by rnicholus** [comment]
Thanks for that. I’ll hopefully taje a closer look soon. The build will need to be fixed here as well, as one of the lint checks is failing

**Comment by rnicholus** [comment]
After looking at this a bit closer, I'm (first) not really sure I understand the problem. And second I don't think the changes here are appropriate at all. I will say the call to `templating.updateThumbnail` in the `_maybeUpdateThumbnail` method of uploader.api.js is incorrect in that it fails to pass a boolean for the third parameter (which is `showWaitingImg`). But it's not clear that this is related to the issue you're having.

**Pull request closed without merging**
