### PR TITLE
Allow an alternate library to be used to generate resized images

### LINKED ISSUE #1525: Use a higher quality image resizing algorithm
Most browsers use [linear interpolation](http://entropymine.com/resamplescope/notes/browsers/) when resizing images. This leads to extreme [aliasing and Moire patterns](http://users.wfu.edu/matthews/misc/DigPhotog/alias/) which is a deal breaker for anyone resizing images for art/photo galleries, albums, etc. These kinds of artifacts are impossible to remove after the fact.

**Edit: For anyone looking for a solution [this](https://github.com/FineUploader/fine-uploader/issues/1525#issuecomment-195617375) is much better than limby-resize.**

A solution I've found is using [limby-resize](https://github.com/danschumann/limby-resize), which resizes images using a custom algorithm to a level of quality similar to imagemagick or photoshop. [Here is a demo](http://output.jsbin.com/palota/1/). Fine Uploader uses the default browser image resizing algorithm AKA the "Crappy" method.

My solution was to replace drawImage in the else statement [at line#168 in megapix-image.js](https://github.com/FineUploader/fine-uploader/blob/050e94d975388512835f3b96856ea209aa9c3fc9/client/js/image-support/megapix-image.js).

I replaced:
        
    else {
          ctx.drawImage(img, 0, 0, width, height);
    }

    canvas.qqImageRendered && canvas.qqImageRendered();

With:

    else {
        var tmpCanvas = document.createElement("canvas");
        tmpCanvas.width = iw;
        tmpCanvas.height = ih;
        var tmpCtx = tmpCanvas.getContext("2d");
        tmpCtx.drawImage(img, 0, 0);
        canvasResize(tmpCanvas, canvas, function () {
            alert("Image resized by limby-resize");
            canvas.qqImageRendered && canvas.qqImageRendered();
        });
    }

And included the limby-resize js file above fineuploader js in my HTML.

It works well and I think this, or another proper image resizing algorithm should be included in Fine-Uploader. it should be an option the user can set in the resizing options as it is significantly more CPU intensive.

### PR DESCRIPTION
**Pull request by rnicholus**
- [x] Create event docs & stub for new callback/event.
- [x] Refactor scaling & thumbnail code to delegate to `customResizer` function (if provided). Support API methods too.
- [x] Determine or if it is possible/reasonable to orient images that are resized using external code.
- [x] Unit tests w/ at least one third-party scaling tool.
- [x] Update scaling & thumbnail feature doc pages.
- [x] Determine the consequences of using 3rd-party scaling code in iOS. If there is an issue here, include docs and/or code to make it easy to bypass third-party scaling code in iOS (or anytime).

closes #1525

### CODE REVIEW

**Comment by rnicholus** [comment]
I have this _mostly_ working at this point. Even though I have some more tasks to complete before calling this "done", it's certainly ready for someone to attempt to test out their favorite resize library alongside Fine Uploader. If anyone is interested in being a tester for this feature, please let me know. Of course, you will also be able to influence the feature before it is completed.

**Comment by rnicholus** [comment]
Core code on this feature is now complete. However, I'm unable to come up with a way to fix large image subsampling in iOS _and_ still make use of one of the suggested third-party image resize libraries. I'm not sure this is even possible, or at least something that can be accomplished without integrating this complex logic into one of the third-party resize libraries. However, Fine Uploader _will_ be able to properly orient all images before passing them off to a third-party resizer. On iOS, the internal resize/scaling code should be used instead of a third-party plug-in. Documentation will include a way to easily implement this behavior.

**Comment by keyeh** [comment]
Great work. I'm ready to test if needed. I'm not targeting iOS, only desktop browsers though.

**Comment by rnicholus** [comment]
Should be ready to test now. I've updated some docs, but not all (see the checkboxes in the pull request description for more details). Assuming you are using pica (and not supporting iOS), want to use pica both for resizing displayed thumbnails _and_ for resizing images to be uploaded, your Fine Uploader initialization code will look like this:

```javascript
var uploader = new qq.FineUploader({
    element: document.getElementById("uploader"),
    request: {
        endpoint: "/upload/endpoint"
    },
    thumbnails: {
        customResizer: function(resizeInfo) {
           return new Promise(function(resolve, reject) {
                pica.resizeCanvas(resizeInfo.sourceCanvas, resizeInfo.targetCanvas, {}, resolve)
           })
        },
        placeholders: {
            waitingPath: "/client/placeholders/waiting-generic.png",
            notAvailablePath: "/client/placeholders/not_available-generic.png"
        }
    },
    scaling: {
        customResizer: function(resizeInfo) {
           return new Promise(function(resolve, reject) {
                pica.resizeCanvas(resizeInfo.sourceCanvas, resizeInfo.targetCanvas, {}, resolve)
           })
        },
        sizes: [...]
    }
})
```

The `scaling` and `thumbnails` option documentation have been updated at http://docs.fineuploader.com/branch/feature_1525-better-scaling/.

**Comment by rnicholus** [comment]
@keyeh Have you had a chance to verify on your end? I'm hoping to finish updating the docs and get this out the door within a week.

**Comment by rnicholus** [comment]
This is ready to be released, and I plan on pushing out Fine Uploader 5.10.0 tomorrow unless I hear back from anyone regarding issue or requested changes.

**Pull request merged**
