### PR TITLE
Add missing return definition

### PR DESCRIPTION
**Pull request by artursvonda**
My env was complaining about implicit any.

## Brief description of the changes
Added return type to a typescript method definition.

### CODE REVIEW

**Comment by SinghSukhdeep** [comment]
@artursvonda anything else you want to push before I merge this?

**Comment by artursvonda** [comment]
@SinghSukhdeep Nope, ok to merge.

**Comment by rnicholus** [comment]
We can either wait for more changes to pile up, or we can release this as a hotfix: 5.14.1, or as the first beta in 5.15.0 (5.15.0-beta1). Thoughts?

**Comment by artursvonda** [comment]
Currently because of this I can't upgrade to a new current stable as it breaks my build. I'd be happier if this was merged sooner rather than later. :)

**Comment by rnicholus** [comment]
roger - i'll push out 5.14.1 ASAP

Future reference: I'd like to see PRs squashed w/ a description commit message when merging into develop. Merge commits just clutter up the branch history. The commit history is easier to parse w/ 1 commit per PR.

**Comment by rnicholus** [comment]
Released in Fine Uploader 15.4.1. Thanks for you work on this @SinghSukhdeep and @artursvonda.

**Pull request merged**
