### PR TITLE
201 created as a succesfull post request response code

### PR DESCRIPTION
**Pull request by burakbostancioglu**
To be able to work with in harmony with django rest framework's CreateModelMixin 201 Created added as a successfull post request response, according to http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

### CODE REVIEW

**Comment by burakbostancioglu** [comment]
@rnicholus Can you halp with this pull request please ?

**Comment by rnicholus** [comment]
Is this for a simple upload request, or for one of the requests sent by Fine Uploader S3/Azure (signature and success)?

**Comment by rnicholus** [comment]
Based on the issue you files, #1354, I'm guessing this is related to the uploadSuccess POST sent by Fine Uploader S3/Azure.

Your pull request is against master, which only contains released code.  Regardless, we'll be sure to make this adjustment in #1314 as part of 5.2.0.

**Comment by burakbostancioglu** [comment]
@rnicholus Thank you so much, it was uploadSuccess POST request. It seems like this is going to be adjusted in 5.2.0 . Thanks!

**Pull request closed without merging**
