### PR TITLE
Feature/flexible upload support

### PR DESCRIPTION
**Pull request by rnicholus**
Replaces #1917, which was closed when the develop branch was removed from the project. See that PR for history.

The following issues will be addressed once this is released:

- #848 
- #1697 
- #1755 
- #1325 
- #1647 
- #1703

Latest release is 5.16.0-RC2 (on npm).

### CODE REVIEW

**Comment by rnicholus** [comment]
Note that I cannot guarantee that this will not break S3 or Azure code as I have no way to run manual tests against either of these (even S3) anymore.

**Comment by SinghSukhdeep** [comment]
@rnicholus do this needs to be reviewed by someone other than you in order to merge?

**Comment by rnicholus** [comment]
a review would be nice, but I am mostly waiting for my own internal testing in a closed source app to reveal any issues before releasing. I am unable to test against S3, so if you or anyone can do that, this would be hlepful.

**Comment by rnicholus** [comment]
Something that came up during manual/internal testing in a real-world app that's using v5.16.0-beta.0: the fact that you can cancel or pause an upload when Fine Uploader is waiting for a chunking success XHR response is problematic. Integrations, such as React Fine Uploader, see that the upload is not yet complete, and that's true, so pause/cancel buttons are rendered. Furthermore, the API accepts pause/cancel commands while in this state?

Why is this bad? Well, it's not guaranteed that the request can be cancelled before the file has been "finalized" on the server fielding the request. So, in the case of a pause, a subsequent resume may result in an error. And if the upload is cancelled at this point, it may still be considered "completed" on the server. So the library should probably be updated as follows:

1. Reject `cancel` and `pause` API calls while in this state.
2. Broadcast a new status change event (such as `qq.status.UPLOAD_FINALIZING`). This will be a signal to integrators that the last byte has been sent, and they can react accordingly. Responses to this state may include removing the cancel/pause buttons and rendering a custom status message ("your file is being verified by the server").

**Comment by xistext** [comment]
When do you think this branch might be merged?  I was hoping to be able to use fine-uploader to access s3 with federated identities but have been stuck for a couple weeks.  It seems like the AWS signed urls might be the ticket.  Do you take donations to help with motivation?  Thanks!

**Comment by rnicholus** [comment]
@xistext I'm sorry - i cannot accept personal donations to influence my time on this project. I'm quite focused on my "day" job at the moment, which is demanding of my time and also spawned all of the substantial changes you see in this PR. I am however actively looking for others to help me regularly maintain this project. 

That said, you can try all of this out now - it's published to npm and I'm using it on a closed source project. The latest release on npm is 5.16.0-RC1, and the description of this PR is updated as the version changes. Once I'm satisfied with the performance in my closed source project, i'll officially release. Please do let me know if you see any issues or have questions though.

P.S. The S3 demo on fineuploader.com/demos has been dead for a while as I don't want to continue paying the AWS bills myself (~$40/month). So if you or anyone else would like to take on this support, that would be helpful.

**Comment by xistext** [comment]
I have installed 5.16.0-RC1.  How do I tell it not to use the signature endpoint but instead to use the signed url?  I am trying to use the url generated by s3.getSignedUrl as the request endpoint.  Thanks!

**Comment by rnicholus** [comment]
Pretty much all of these changes focus on the traditional non-s3/azure uploaders. Note that `onUpload` and `onUploadChunk` events both accept a `Promise` as a return value. You can either use whichever methods you choose in `onUpload` to influence the file to be uploaded, or you can do so in each `onUploadChunk` handler by resolving your `Promise` with and object that contains an `endpoint` URI.

**Comment by rnicholus** [comment]
Docs at https://docs.fineuploader.com/tag/5.16.0-RC1/

**Comment by xistext** [comment]
I tried setting the signature endpoint as the docs specify '/s3/signature' but get an error 'Failed to load resource: the server responded with a status of 405 (Method Not Allowed)' on that url when I upload my image.  I have tried setting version:4 or not but saw no difference.  Thanks for your replies.

**Comment by Bhupadhy** [comment]
Hello @rnicholus,

Im interested in using the per-file chunk sizes in my project with a stable version of fineuploader. I am thinking of forking the latest stable version and adding the commits which relate to that feature. Would something like this be possible? Which commits beyond 8eb98d7 and 53b397d relate to this feature? I have been using this feature in development and it seems to work well.

Thanks for your work on this project

**Comment by uriahcarpenter** [comment]
I may be able to provide some delegated S3 buckets from our corporate account to keep smoke tests viable. PM me if interested.

**Comment by rnicholus** [comment]
Thanks @uriahcarpenter. Will do.

**Comment by rnicholus** [comment]
@Bhupadhy is the current RC1 working will for you?

**Comment by Bhupadhy** [comment]
@rnicholus ,

I am currently using RC1 and I haven't ran into any issues yet.

**Comment by rnicholus** [comment]
I'm planning to release this as v5.16.0 very soon. I'd like to fit in this update as well - https://github.com/FineUploader/fine-uploader/pull/1939#issuecomment-352971246 - but I don't believe this is a regression, and may just push that out afterwards as v5.16.1.

**Pull request merged**
