### PR TITLE
feat(dnd.js): add dragEnter and dragLeave callbacks

### PR DESCRIPTION
**Pull request by HerringtonDarkholme**
## Brief description of the changes
Currently fine-uploader dnd only toggles class name on targetElement. However, users need more advanced UI control when dragging/drop.

## What browsers and operating systems have you tested these changes on?
Firefox

## Have you written unit tests? If not, explain why.
No. I didn't find other callbacks for dnd like `processingDroppedFilesComplete` in unit test. So I think it might be better to ask maintainers how to add it.

### CODE REVIEW

**Comment by SinghSukhdeep** [comment]
I hear you, I will look at this closely soon and will try my best

**Comment by HerringtonDarkholme** [comment]
Thank you for taking up the project!

**Comment by SinghSukhdeep** [comment]
Hoping to get some time soon to look at all the pending PRs

**Comment by SinghSukhdeep** [comment]
Everything looks good.
This also requires docs update for [drag and drop page](https://docs.fineuploader.com/branch/master/features/drag-and-drop.html)
Can you please add that as well and I'll merge this

**Comment by HerringtonDarkholme** [comment]
Thanks!

**Pull request merged**
