### PR TITLE
Workaround / fix for multi-part upload to S3 fails on Edge >= 15 with 403 Forbidden

### PR DESCRIPTION
**Pull request by galvinhsiu**
## Brief description of the changes
IE Edge 15+ (by default) appears to send over the "content-type" header implicitly when performing multi-part uploads.  This causes grief when uploading to S3 since it would hard fail on the authorization header.

This workaround / fix attempts to detect if this is IE edge and if there is no content-type header passed in, will remove the content-type header when uploading the chunk.

Please refer to:
https://github.com/FineUploader/fine-uploader/issues/1852

Recommendations / comments are welcome.

## What browsers and operating systems have you tested these changes on?
Safari on Mac Sierra
< Firefox 50, > Firefox 50 on Mac Sierra
IE11 on Windows 10 / 8
Edge 14, Edge 15+ on Windows 10

## Have you written unit tests? If not, explain why.
Yes, see attached code.

### CODE REVIEW

**Comment by rnicholus** [comment]
why are we singling out Edge here? why not just do this for all browsers?

**Comment by galvinhsiu** [comment]
@rnicholus - great idea. going to update the PR

**Comment by galvinhsiu** [comment]
@rnicholus any feedback on this PR?

**Comment by rnicholus** [comment]
Sorry for the delay. I'm in the process of moving Fine Uploader to a free/self-sustainable services before I step away from the project completely. Also looking for a new maintainer.

I'm merging your changes now.

**Pull request merged**
