### PR TITLE
fix(dnd): ignore non-file drag'n'drop events

### LINKED ISSUE #1588: Fine-uploader seems to catch every drag'n'drop JS events.
## Type of issue

bug
## Uploader type

traditional
## Bug details

It seems that after initializing fine-uploader, it is impossible to drag some text, from an external program (i.e. gedit) to a simple HTML textarea. Even if there is no drag'n'drop zone. Actually I do not have one, on purpose.
### Fine Uploader version

5.9.0
### Browsers where the bug is reproducible

Firefox
### Operating systems where the bug is reproducible

Fedora 23
### Exact steps required to reproduce the issue
1. Create a blank page with a fine-uploader and a textarea
2. Try to drag'n'drop some text into the textarea
3. See that no text is dropped.
### All of your Fine Uploader initialization JavaScript code

Is it relevant?

``` javascript
    var uploader = new qq.FineUploader({
        element: document.getElementById('file-uploader'),
        request: {
            endpoint: '/upload_push/',
            customHeaders: {
                "X-CSRFToken": Cookies.get("csrftoken")
            },
            params: {
                'foo': bar,
            },
        },
        deleteFile: {
            enabled: true,
            endpoint: '/upload_delete',
            customHeaders: {
                "X-CSRFToken": Cookies.get("csrftoken")
            },
        },
        session: {
            endpoint: '/upload_filelist/' + id,
            customHeaders: {
                "X-CSRFToken": Cookies.get("csrftoken")
            },
        },
        sizeLimit: 5000000, // 5Mo
        minSizeLimit: 1,
    });
```
### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)

``` html
<script type="text/template" id="qq-template">
    <div class="qq-uploader-selector qq-uploader">
        <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
            <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
        </div>
        <div class="qq-upload-button-selector qq-upload-button">
            <div>Téléverser un fichier</div>
        </div>
            <span class="qq-drop-processing-selector qq-drop-processing">
                <span>Traîtement des fichiers...</span>
                <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
            </span>
        <ul class="qq-upload-list-selector qq-upload-list" aria-live="polite" aria-relevant="additions removals">
            <li>
                <div class="qq-progress-bar-container-selector">
                    <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
                </div>
                <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                <span class="qq-upload-file-selector qq-upload-file"></span>
                <span class="qq-edit-filename-icon-selector qq-edit-filename-icon" aria-label="Edit filename"></span>
                <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                <span class="qq-upload-size-selector qq-upload-size"></span>
                <button type="button" class="qq-btn qq-upload-cancel-selector qq-upload-cancel">Annuler</button>
                <button type="button" class="qq-btn qq-upload-retry-selector qq-upload-retry">Réessayer</button>
                <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">Supprimer</button>
                <span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
            </li>
        </ul>

        <dialog class="qq-alert-dialog-selector">
            <div class="qq-dialog-message-selector"></div>
            <div class="qq-dialog-buttons">
                <button type="button" class="qq-cancel-button-selector">Fermer</button>
            </div>
        </dialog>

        <dialog class="qq-confirm-dialog-selector">
            <div class="qq-dialog-message-selector"></div>
            <div class="qq-dialog-buttons">
                <button type="button" class="qq-cancel-button-selector">Non</button>
                <button type="button" class="qq-ok-button-selector">Oui</button>
            </div>
        </dialog>

        <dialog class="qq-prompt-dialog-selector">
            <div class="qq-dialog-message-selector"></div>
            <input type="text">
            <div class="qq-dialog-buttons">
                <button type="button" class="qq-cancel-button-selector">Annuler</button>
                <button type="button" class="qq-ok-button-selector">Ok</button>
            </div>
        </dialog>
    </div>
</script>
```
### Detailed explanation of the problem

See `bug details`.

### PR DESCRIPTION
**Pull request by Novex**
## Brief description of the changes
Since we only deal with files, it makes sense to ignore all events non-file related (eg. dragging
plaintext). This commit fixes a few things that have changed in the browsers which subtly break
the current checks.

* The `contains` function on `dt.files` has been removed from the spec and will always return
  undefined. Except for IE, which hasn't implemented the change.
  * Chrome and Firefox have replaced it with `includes`, which we now use
  * We've left a `contains` check in there for IE as a last resort
  * Remove the comment about it being Firefox only, since it also works in Chrome now
  * More info re: removal at: https://github.com/tc39/Array.prototype.includes#status

* The dt.files property always seems to be an empty array for non-drop events. Empty arrays are
  truthy, and so this will always satisfy the `isValidFileDrag` check before it can validate that
  the types array includes files
  * It will now only be truthy if the files array actually contains entries

* There is a drop handler which binds to the document and always prevents all default drop
  behaviour from occurring, including things like dropping text into textfields
  * It will now only prevent default behaviour for file drops, which has the handy side-effect
    of preventing the page from navigating to the dropped file if the user misses the dropzone.

Fixes #1588.

## What browsers and operating systems have you tested these changes on?
Chrome 57, Firefox 52 and IE11 on Windows 8.1

## Have you written unit tests? If not, explain why.
Yes!

Though I had to use mock objects because we can't edit the fields we need to on the 
DragEvent/DataTransfer. Suggestions for improvements very welcome :)

### CODE REVIEW

**Comment by ramusus** [comment]
I'm really interested to get this PR merged into any upcoming release. Is there any chance to get it there?

**Comment by ramusus** [comment]
Great work @Novex! I investigate this issue myself and came to the same conclusions - the problem in `isValidFileDrag`. It's outdated and doesn't let Fineuploader to work together with drag-and-drop libraries, for example [react-dnd](https://github.com/react-dnd/react-dnd).

BTW, I see the Travis crashed because of just one trailing whitespace.. It shouldn't be difficult to fix.

**Comment by rnicholus** [comment]
As luck would have it - i may need this fix for one of my projects too! So I'll be looking closer at this very soon. I independently verified a similar approach, and I too am trying to integrate Fine Uploader on a page w/ react-dnd.

**Comment by rnicholus** [comment]
All moderns browsers check out _except_ for Edge 41. I'll look closer tomorrow in hopes that Edge can be easily covered too.

**Comment by rnicholus** [comment]
False alarm - caching issue in Edge caused the above problem. Looks like we're clear to merge and release as v5.15.2. I'll do that very soon.

**Comment by ramusus** [comment]
@rnicholus For some reason v.5.15.2 doesn't contain fixes from this PR.
Could you, please, check what version uploaded to npm with label 5.15.2?

**Comment by rnicholus** [comment]
Just released 5.15.3 which should contain the fix. All of my other projects lack a develop branch, and I overlooked the fact that Fine Uploader has a develop branch in addition to master, which caused some confusion for me when publishing. I removed develop today to prevent this from happening in the future since develop isn't really serving a purpose anymore.

**Comment by ramusus** [comment]
@rnicholus thanks, it's workinс!

**Comment by Novex** [comment]
Hooray! Thank you for merging this 🎉

**Pull request merged**
