### PR TITLE
Feature/typescript definitions

### PR DESCRIPTION
**Pull request by SinghSukhdeep**
## Brief description of the changes [REQUIRED]
Adding TypeScript definitions allows integration with TypeScript based projects

## What browsers and operating systems have you tested these changes on? [REQUIRED]
N/A

## Are all automated tests passing? [REQUIRED]
Need to write automated tests during code reviews or afterwards

## Is this pull request against develop or some other non-master branch? [REQUIRED]
Yes

### CODE REVIEW

**Comment by SinghSukhdeep** [comment]
PR #1689 Continued here

**Comment by rnicholus** [comment]
I'm curious what is left before this can be pushed though. Is there anything I can do to help?

**Comment by SinghSukhdeep** [comment]
I'll add that method's definition.
I don't have anything more left to write, I just wanted if someone could review the definitions.
Other than that everything is ok from my side.

About the new method:
Docs don't really specify the type for `id` parameter, whose id is it and what the parameter is supposed to do. So I just wrote whatever is there right now

**Comment by rnicholus** [comment]
IDs are always file IDs

**Comment by rnicholus** [comment]
I'll spot check the defs, there are too many to  completely review. We should be able to eliminate the definitely typed defs after this is merged, correct?

**Comment by SinghSukhdeep** [comment]
Yes the definitely typed defs should be eliminated after this

**Comment by rnicholus** [comment]
After a quick glance, everything looks good, except for one thing - in cases where Fine Uploader returns a "Promise", it actually returns a [`qq.Promise`](http://docs.fineuploader.com/branch/master/features/async-tasks-and-promises.html), which is Fine Uploader's completely non-standard Promise implementation that I wrote which predates the spec, or at least my awareness of the spec. I have an open case to fix this - #1642 - but that would be a breaking change and can't happen until at least 6.0.

**Comment by SinghSukhdeep** [comment]
Ok, I'll take a look at `qq.Promise` and make changes to functions that are returning a promise. Later after 6.0 release, we'll update the def to return native Promise

**Comment by rnicholus** [comment]
Excellent! One more thing - will these defs be picked up when Fine Uploader is installed via npm? It doesn't look like they are even part of the npm package, since the `Makefile`'s `setup-dist` recipe contains the logic for generating the package, and the typescript folder is new. You should be able to test before even publishing to npm by following these steps:

1. `make public simulate=true`
2. `cd _dist/5.14.0-beta1`
3. `npm link`
4. Go to whatever directory/project you want to install Fine Uploader to
5. `npm link fine-uploader`
6. Make sure your TS project is able to see the defs.

**Comment by SinghSukhdeep** [comment]
Little typo in the docs [here](http://docs.fineuploader.com/branch/master/features/async-tasks-and-promises.html#failure).
It should say `Call this on a promise to indicate failure.` instead of `Call this on a promise to indicate success.`

**Comment by SinghSukhdeep** [comment]
I'll work on including the Typescript folder in the build process whenever I get some time

**Comment by rainstormza** [comment]
+1

**Comment by SinghSukhdeep** [comment]
@rnicholus I've updated `Makefile` to include typescript directory and has followed the steps you stated earlier to test changes. New project can see the defs no problem. Please review

**Comment by rnicholus** [comment]
Tweeted from the Fine Uploader account, but couldn't find your Twitter account. https://twitter.com/fineuploader/status/830975906852241412

**Comment by SinghSukhdeep** [comment]
Thanks for your prompt support. I'll add the new method in def file.
My Twitter handle is Sukh9212.
Thanks for the tweet as well

**Comment by don-bluelinegrid** [comment]
There is still an index.d.ts missing, and as a result the d.ts files inside the `/typescript` directory are not being automatically found by TypeScript.

**Comment by don-bluelinegrid** [comment]
Also, there is no `export` statement in the typing file, so nothing is being picked up as a default export.

There needs to be a default export of `qq`.

**Comment by SinghSukhdeep** [comment]
@don-bluelinegrid see PR #1840 
Current TS definitions do not support ES6 style import.
You will have to include the fine uploader js file in your html page and follow [this](https://github.com/FineUploader/fine-uploader/blob/develop/client/typescript/fine-uploader.test.ts) file for syntax guidance

**Comment by don-bluelinegrid** [comment]
I am not going to do that.

I'm using TypeScript and webpack, and every `module` that's provided as an npm package can be imported using an `import` statement.  I don't include any JS files in my `index.html`, and I don't plan to start doing that.

I read various PRs talking about TypeScript compatibility, and I see typescript `d.ts` files in the package.  Why do these exist, if there is no TypeScript compatibility?

**Comment by SinghSukhdeep** [comment]
As I said earlier, we are providing the typescript definitions. Current way of consumption is as I wrote in my previous comment.
We are going to provide `import` support soon.
Just be patient.

**Comment by SinghSukhdeep** [comment]
#1840 has been merged and released as 5.15.0
Happy Importing !!

**Pull request merged**
