### PR TITLE
handle 204 no content situation

### PR DESCRIPTION
**Pull request by Darmody**
## Brief description of the changes [REQUIRED]
Give default value `'{}'` to json parser for 204 response

## What browsers and operating systems have you tested these changes on? [REQUIRED]
All browsers

## Are all automated tests passing? [REQUIRED]
yes

## Is this pull request against develop or some other non-master branch? [REQUIRED]
Sorry, not sure what this question mean? Maybe yes.

### CODE REVIEW

**Comment by rnicholus** [comment]
I'm fairly certain that this change is not sufficient, and an empty response will still be marked as a failed request. See the `isErrorUploadResponse` function.

**Comment by Darmody** [comment]
@rnicholus Hi.

https://github.com/Darmody/fine-uploader/blob/master/client/js/traditional/traditional.xhr.upload.handler.js#L77-L81

I think `isErrorUploadResponse` treat `204` as a success response. So that `parseResponse` will try to parse an empty `responseText`.

https://github.com/FineUploader/fine-uploader/blob/c1b4954f21381dbd664e379abf571c988e2265c0/client/js/traditional/traditional.xhr.upload.handler.js#L103

**Comment by rnicholus** [comment]
The request will be marked as an error the `success` property of the response is "falsy". An empty object falls into that category.

**Comment by Darmody** [comment]
@rnicholus Oh, sorry. I caught your point now.

**Comment by Darmody** [comment]
@rnicholus Is it sufficient now?

**Comment by rnicholus** [comment]
I don't think so. This could have a substantial impact on existing servers that depend on the current behavior. In other words, even if the response code is 2xx, you can signal an error simply by _not_ returning a JSON response with a `success: true` property. This was especially important in IE9 and older, which are still technically supported by Fine Uploader.

I would consider this a breaking change, and, as a result, I can't release this without moving to version 6.0.0. I do have a (stale) v6 branch which I hope to get back to at some point. In that branch, I may very well remove support for all but the most current browsers (support for anything older than IE11 will be gone). There are likely already some open cases that are targeted for 6.0 that should make the response handling logic less awful.

**Comment by Darmody** [comment]
@rnicholus I see, then I will close this one.

**Comment by rnicholus** [comment]
Thanks for you time. Sorry I couldn't merge this in.

**Pull request closed without merging**
