### PR TITLE
Don't requeue uploads in the waiting queue.

### PR DESCRIPTION
**Pull request by fromkeith**
## Brief description of the changes [REQUIRED]

Stop the connection manager from pushing an existing id into the waiting queue.

If the user calls retry twice (or any other weird race condition) the connection manager re-queues the file. Then when 'free' is called, we see that this id exists in the waiting queue. Thus we don't free the open slot or invoke the next item for upload.
This can cause the uploader to stop working entirely as the open slots are never cleared.
## What browsers and operating systems have you tested these changes on? [REQUIRED]

Chrome on Windows 10.
## Are all automated tests passing? [REQUIRED]

Yes.
## Is this pull request against develop or some other non-master branch? [REQUIRED]

Yes. Going to Develop. Did discover this issue when using 5.10.

Fixing a bug where if 'retry' is invoked on an item already in the waiting queue it gets re-queued. Which means that after the upload finishes and 'free' is called, we incorrectly don't upload the next item.

### CODE REVIEW

**Comment by rnicholus** [comment]
Thanks so much for detecting this issue and contributing a fix. I'll run some manual regression tests to confirm that everything is still working as expected (since upload.handler.controller.js is both critical and complex). If everything checks out, I'll merge this in.

Also, can you please sign the CLA?

**Comment by rnicholus** [comment]
Can you please merge develop back into this branch?

**Comment by rnicholus** [comment]
I'm going to push this to 5.11.10, as I'd like to get 5.11.9 out as soon as possible and I have yet to even start on some of those bug fixes.

**Comment by rnicholus** [comment]
This is still on my radar, but 5.11.9 is going to be my focus first. This fix is scheduled for 5.11.10.

**Comment by rnicholus** [comment]
Looks like a _lot_ of changes have been added to this branch, unrelated to the original problem. Was this by mistake?

**Comment by fromkeith** [comment]
wow... yea...
thats not supposed to be in there..

**Comment by fromkeith** [comment]
Fixed hopefully...

**Comment by rnicholus** [comment]
Yep, thanks. Trying to be as transparent as possible: the number of cases for me to look into/verify is piling up, and, unfortunately, the amount of time I have to dedicate to this project is rapidly decreasing.

**Comment by rnicholus** [comment]
Going to have to push this to 5.11.11. I have to hotfixes ready for 5.11.10, and I'd like to release that today. I haven't gotten around to testing this one yet, and it's more risky than the others. At least one unit test needs to be written for this anyway, and I'm not sure when I'll get to that, so if you are able to contribute one, that will speed things up a bit.

**Pull request closed without merging**
